
export const TIMEZONES:any[]=[
  { title: 'Greenwich Mean Time (GMT)', value: 0, index: 1 },
  { title: 'Coordinated Universal Time (UTC)', value: 0, index: 2 },
  { title: 'Eastern Standard Time (EST)', value: -5, index: 3 },
  { title: 'Central Standard Time (CST)', value: -6, index: 4 },
  { title: 'Mountain Standard Time (MST)', value: -7, index: 5 },
  { title: 'Pacific Standard Time (PST)', value: -8, index: 6 },
  { title: 'Alaska Standard Time (AKST)', value: -9, index: 7 },
  { title: 'Hawaii-Aleutian Standard Time (HST)', value: -10, index: 8 },
  { title: 'Eastern European Time (EET)', value: 2, index: 9 },
  { title: 'Central European Time (CET)', value: 1, index: 10 },
  { title: 'Mountain Daylight Time (MDT)', value: -6, index: 11 },
  { title: 'Pacific Daylight Time (PDT)', value: -7, index: 12 },
  { title: 'Eastern Daylight Time (EDT)', value: -4, index: 13 },
  { title: 'Central Daylight Time (CDT)', value: -5, index: 14 },
  { title: 'Australian Eastern Standard Time (AEST)', value: 10, index: 15 },
  { title: 'Australian Central Standard Time (ACST)', value: 9, index: 16 },
  { title: 'Australian Western Standard Time (AWST)', value: 8, index: 17 },
  { title: 'Japan Standard Time (JST)', value: 9, index: 18 },
  { title: 'Indian Standard Time (IST)', value: 5, index: 19 },
  { title: 'China Standard Time (CST)', value: 8, index: 20 },
  { title: 'Eastern African Time (EAT)', value: 3, index: 21 },
  { title: 'Central African Time (CAT)', value: 2, index: 22 },
  { title: 'Atlantic Standard Time (AST)', value: -4, index: 23 },
  { title: 'Newfoundland Standard Time (NST)', value: -3, index: 24 },
  { title: 'Brasília Time (BRT)', value: -3, index: 25 },
  { title: 'Eastern Indonesia Time (WIT)', value: 9, index: 26 },
  { title: 'Central Indonesia Time (CIT)', value: 8, index: 27 },
  { title: 'Western Indonesia Time (WIB)', value: 7, index: 28 },
  { title: 'Moscow Standard Time (MSK)', value: 3, index: 29 },
  { title: 'Indian Standard Time (IST)', value: 5, index: 30 },
  { title: 'Arabian Standard Time (AST)', value: 3, index: 31 },
  { title: 'South Africa Standard Time (SAST)', value: 2, index: 32 },
  { title: 'Central European Summer Time (CEST)', value: 2, index: 33 },
  { title: 'British Summer Time (BST)', value: 1, index: 34 },
  { title: 'Central Daylight Time (CDT)', value: -5, index: 35 },
  { title: 'Eastern Daylight Time (EDT)', value: -4, index: 36 },
  { title: 'Pacific Daylight Time (PDT)', value: -7, index: 37 },
  { title: 'Mountain Daylight Time (MDT)', value: -6, index: 38 },
  { title: 'Eastern European Summer Time (EEST)', value: 3, index: 39 },
  { title: 'Central European Summer Time (CEST)', value: 2, index: 40 },
  { title: 'Greenwich Mean Time (GMT)', value: 0, index: 41 },
  { title: 'Coordinated Universal Time (UTC)', value: 0, index: 42 },
  { title: 'Central Standard Time (CST)', value: -6, index: 43 },
  { title: 'Eastern Standard Time (EST)', value: -5, index: 44 },
  { title: 'Pacific Standard Time (PST)', value: -8, index: 45 },
  { title: 'Mountain Standard Time (MST)', value: -7, index: 46 }
];
