

let timeZones:any[]=[
  { title: '(UTC+0) Greenwich Mean Time (GMT)', value: 0, index: 1 },
  { title: '(UTC+0) Coordinated Universal Time (UTC)', value: 0, index: 2 },
  { title: '(UTC-5) Eastern Standard Time (EST)', value: -5, index: 3 },
  { title: '(UTC-6) Central Standard Time (CST)', value: -6, index: 4 },
  { title: '(UTC-7) Mountain Standard Time (MST)', value: -7, index: 5 },
  { title: '(UTC-8) Pacific Standard Time (PST)', value: -8, index: 6 },
  { title: '(UTC-9) Alaska Standard Time (AKST)', value: -9, index: 7 },
  { title: '(UTC-10) Hawaii-Aleutian Standard Time (HST)', value: -10, index: 8 },
  { title: '(UTC+2) Eastern European Time (EET)', value: 2, index: 9 },
  { title: '(UTC+1) Central European Time (CET)', value: 1, index: 10 },
  { title: '(UTC-6) Mountain Daylight Time (MDT)', value: -6, index: 11 },
  { title: '(UTC-7) Pacific Daylight Time (PDT)', value: -7, index: 12 },
  { title: '(UTC-4) Eastern Daylight Time (EDT)', value: -4, index: 13 },
  { title: '(UTC-5) Central Daylight Time (CDT)', value: -5, index: 14 },
  { title: '(UTC+10) Australian Eastern Standard Time (AEST)', value: 10, index: 15 },
  { title: '(UTC+9) Australian Central Standard Time (ACST)', value: 9, index: 16 },
  { title: '(UTC+8) Australian Western Standard Time (AWST)', value: 8, index: 17 },
  { title: '(UTC+9) Japan Standard Time (JST)', value: 9, index: 18 },
  { title: '(UTC+5) Indian Standard Time (IST)', value: 5, index: 19 },
  { title: '(UTC+8) China Standard Time (CST)', value: 8, index: 20 },
  { title: '(UTC+3) Eastern African Time (EAT)', value: 3, index: 21 },
  { title: '(UTC+2) Central African Time (CAT)', value: 2, index: 22 },
  { title: '(UTC-4) Atlantic Standard Time (AST)', value: -4, index: 23 },
  { title: '(UTC-3) Newfoundland Standard Time (NST)', value: -3, index: 24 },
  { title: '(UTC-3) Brasília Time (BRT)', value: -3, index: 25 },
  { title: '(UTC+9) Eastern Indonesia Time (WIT)', value: 9, index: 26 },
  { title: '(UTC+8) Central Indonesia Time (CIT)', value: 8, index: 27 },
  { title: '(UTC+7) Western Indonesia Time (WIB)', value: 7, index: 28 },
  { title: '(UTC+3) Moscow Standard Time (MSK)', value: 3, index: 29 },
  { title: '(UTC+3) Arabian Standard Time (AST)', value: 3, index: 31 },
  { title: '(UTC+2) South Africa Standard Time (SAST)', value: 2, index: 32 },
  { title: '(UTC+2) Central European Summer Time (CEST)', value: 2, index: 33 },
  { title: '(UTC+1) British Summer Time (BST)', value: 1, index: 34 },
  { title: '(UTC-8) Pacific Standard Time (PST)', value: -8, index: 45 }
]
const uniqueTimeZones = [...new Map(timeZones.map(item => [item.value, item])).values()];
export const TIMEZONES:any[]=uniqueTimeZones
